// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5pvmkrH8ckECuVVc82HFgU9j5ovUAeV8',
    appId: '1:311992519988:web:8301fe1fbca8c75c6da961',
    messagingSenderId: '311992519988',
    projectId: 'natgard-shop',
    authDomain: 'natgard-shop.firebaseapp.com',
    databaseURL: 'https://natgard-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'natgard-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5pvmkrH8ckECuVVc82HFgU9j5ovUAeV8',
    appId: '1:311992519988:android:e3666057f1c1b27c6da961',
    messagingSenderId: '311992519988',
    projectId: 'natgard-shop',
    storageBucket: 'natgard-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5pvmkrH8ckECuVVc82HFgU9j5ovUAeV8',
    appId: '1:311992519988:android:e3666057f1c1b27c6da961',
    messagingSenderId: '311992519988',
    projectId: 'natgard-shop',
    storageBucket: 'natgard-shop.appspot.com',
    iosBundleId: 'ru.natgard.natgard-appMobile',
  );
}
