name: client_mobile
description: "Natgard shop."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  enum_assist_annotation: ^0.1.0+1
  json_annotation: ^4.8.1
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.4
  flutter_downloader: ^1.11.8
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  shared:
    path: "../shared"
  firebase_app_check: ^0.3.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  elementary_test: ^2.0.1
  retrofit_generator: ^9.1.2
  golden_toolkit: 0.15.0
  build_runner: ^2.4.6
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.1
  flutter_staggered_grid_view: ^0.7.0
  mocktail: 1.0.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
